import type { Metadata } from "next";
import { ReactElement } from "react";
import { Roboto, Playfair } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/MainHeader/MainHeader";
import Header from "@/components/Header/Header";
import MainNavigation from "@/components/MainNavigation/MainNavigation";

// Fonts
const robotoFont = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500'],
  variable: '--font-roboto',
  display: 'swap',
})

const playfairFont = Playfair({
  subsets: ['latin', 'cyrillic'],
  weight: ['700'],
  variable: '--font-playfair',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: ReactElement;
}>): ReactElement {
  return (
    <html lang="ru">
    <body className={`${robotoFont.variable} ${playfairFont.variable}`}>
    <MainHeader />
    <Header />
    <MainNavigation />
    {children}
    </body>
    </html>
  );
}
